-- Creates the demo "books" table used by the PHPUnit CRUD test suite.
-- Runs on every container start (see 01_create_user.sql), right after it.
--
-- Each *.sql file under scripts/startup is run as its own fresh
-- "sqlplus / as sysdba" session (see /opt/oracle/runUserScripts.sh), which
-- connects to the CDB root by default -- it does NOT inherit 01's PDB
-- context. Without switching container again, ALTER SESSION SET
-- CURRENT_SCHEMA fails with ORA-01435 (user does not exist), since testuser
-- is a PDB-local user.
--
-- Identifiers are double-quoted lowercase so Oracle stores them exactly as
-- written. Left unquoted, Oracle folds them to uppercase, which then breaks
-- CakePHP's schema reflection: Table/Entity code here refers to "id",
-- "title", etc. and BooksTable::getSchema()->getColumnType('id') returns
-- null (assert failure) unless the reflected column key also reads "id".
--
-- Oracle Database 23c/23ai added the "IF NOT EXISTS" clause for CREATE TABLE,
-- so this stays idempotent without a DROP/PL-SQL guard block.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = testuser;

-- "authors" is created before "books" because "books"."author_id" carries a
-- foreign key to it. It is intentionally independent of the pre-existing
-- "books"."author" VARCHAR2 column (which stays as-is so the existing
-- CRUD/Query test suites keep working unmodified): "author_id" only backs
-- the ORM association (contain()) tests.
CREATE TABLE IF NOT EXISTS "authors" (
    "id"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "books" (
    "id"        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "title"     VARCHAR2(255) NOT NULL,
    "author"    VARCHAR2(255) NOT NULL,
    "author_id" NUMBER REFERENCES "authors"("id"),
    "price"     NUMBER(10,2) DEFAULT 0 NOT NULL,
    "created"   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "modified"  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

EXIT;
