-- Creates the demo "books" table used by the PHPUnit CRUD test suite.
-- Runs on every container start (see 01_create_user.sql), right after it.
--
-- Each *.sql file under scripts/startup is run as its own fresh
-- "sqlplus / as sysdba" session (see /opt/oracle/runUserScripts.sh), which
-- connects to the CDB root by default -- it does NOT inherit 01's PDB
-- context. Without switching container again, ALTER SESSION SET
-- CURRENT_SCHEMA fails with ORA-01435 (user does not exist), since testuser
-- is a PDB-local user.
--
-- Identifiers are double-quoted lowercase so Oracle stores them exactly as
-- written. Left unquoted, Oracle folds them to uppercase, which then breaks
-- CakePHP's schema reflection: Table/Entity code here refers to "id",
-- "title", etc. and BooksTable::getSchema()->getColumnType('id') returns
-- null (assert failure) unless the reflected column key also reads "id".
--
-- Oracle Database 23c/23ai added the "IF NOT EXISTS" clause for CREATE TABLE,
-- so this stays idempotent without a DROP/PL-SQL guard block.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = testuser;

CREATE TABLE IF NOT EXISTS "books" (
    "id"       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "title"    VARCHAR2(255) NOT NULL,
    "author"   VARCHAR2(255) NOT NULL,
    "price"    NUMBER(10,2) DEFAULT 0 NOT NULL,
    "created"  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "modified" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

EXIT;
